IF EXISTS(SELECT * FROM sys.databases WHERE NAME ='DB_CLINICA') DROP DATABASE DB_CLINICA;
CREATE DATABASE  DB_CLINICA
	ON
	(
	NAME = DB_CLINICA_DAT,
	FILENAME= N'C:\Users\ta0510\Documents\Sinqia_AspNet\Data\DbClinica.mdf', 
	SIZE = 5000KB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=1000KB
	)
	LOG ON
	 (
	 NAME = DB_CLINICA_LOG,
	FILENAME= N'C:\Users\ta0510\Documents\Sinqia_AspNet\Data\DbClinica_log.ldf', 
	SIZE = 2000KB,
	MAXSIZE=UNLIMITED,
	FILEGROWTH=1000KB
	);

